version: '3.8'

services:
  jobmanager:
    build: .
    image: flink-nexmark-java
    container_name: jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
        state.backend: rocksdb
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092
    networks:
      - nexmark-network
    extra_hosts:
      - "kafka1:172.18.0.3"

  taskmanager:
    build: .
    image: flink-nexmark-java
    container_name: taskmanager
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092
    networks:
      - nexmark-network
    extra_hosts:
      - "kafka1:172.18.0.3"

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexmark
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - nexmark-network

  adminer:
    image: adminer
    ports:
      - "18080:8080"
    networks:
      - nexmark-network
    depends_on:
      - postgres

networks:
  nexmark-network:
    external: true
    name: nexmark-bench_default

volumes:
  postgres_data:
