{
 "title": "Flink + RocksDB - Block Cache Experiment Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Task Manager CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live SST file size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_live_sst_files_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_live_sst_files_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Access Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "State Access Latency (P=0.5)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{quantile=\"0.5\"} / 1e3",
       "legendFormat": "{{state_name}} quantile={{quantile}}"
      }
     ]
    },
    {
     "title": "State Access Latency (P=0.75)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{quantile=\"0.75\"} / 1e3",
       "legendFormat": "{{state_name}} quantile={{quantile}}"
      }
     ]
    },
    {
     "title": "State Access Latency (P=0.95)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{quantile=\"0.95\"} / 1e3",
       "legendFormat": "{{state_name}} quantile={{quantile}}"
      }
     ]
    },
    {
     "title": "State Access Latency (P=0.98)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{quantile=\"0.98\"} / 1e3",
       "legendFormat": "{{state_name}} quantile={{quantile}}"
      }
     ]
    },
    {
     "title": "State Access Latency (P=0.99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{quantile=\"0.99\"} / 1e3",
       "legendFormat": "{{state_name}} quantile={{quantile}}"
      }
     ]
    },
    {
     "title": "State Access Latency (P=0.999)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{quantile=\"0.999\"} / 1e3",
       "legendFormat": "{{state_name}} quantile={{quantile}}"
      }
     ]
    }
   ]
  },
  { "title": "Block Cache Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Block Cache Capacity (Right)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_block_cache_capacity",
     "legendFormat": "Block Cache Capacity (Right)"
    }
   ]
  },
  {
   "title": "Block Cache Capacity (Left)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_block_cache_capacity",
     "legendFormat": "Block Cache Capacity (Left)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Block Cache usage (Right)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_block_cache_usage",
     "legendFormat": "Block Cache Capacity (Right)"
    }
   ]
  },
  {
   "title": "Block Cache Usage (Left)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_block_cache_usage",
     "legendFormat": "Block Cache Pinned Usage (Left)"
    }
   ]
  },
  {
   "title": "Block Cache Pinned Usage (Right)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_block_cache_pinned_usage",
     "legendFormat": "Block Cache Pinned Usage (Right)"
    }
   ]
  },
  {
   "title": "Block Cache Pinned Usage (Left)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_block_cache_pinned_usage",
     "legendFormat": "Block Cache Pinned Usage (Left)"
    }
   ]
  },
  {
   "title": "Block Cache Pinned (Right)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_block_cache_pinned_usage",
     "legendFormat": "Block Cache Pinned (Right)"
    }
   ]
  },
  {
   "title": "Block Cache Pinned (Left)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_block_cache_pinned_usage",
     "legendFormat": "Block Cache Pinned (Left)"
    }
   ]
  },
  {
   "title": "Active Memtable Size (Right)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_cur_size_active_mem_table",
     "legendFormat": "Active Memtable Size (Right)"
    }
   ]
  },
  {
   "title": "Active Memtable Size (Left)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_cur_size_active_mem_table",
     "legendFormat": "Active Memtable Size (Left)"
    }
   ]
  },
  {
   "title": "All Memtable Size (Right)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_cur_size_all_mem_tables",
     "legendFormat": "All Memtable Size (Right)"
    }
   ]
  },
  {
   "title": "All Memtable Size (Left)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_cur_size_all_mem_tables",
     "legendFormat": "All Memtable Size (Left)"
    }
   ]
  },
  { "title": "Cache Miss Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Data Block Cache Hits/Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_data_miss",
     "legendFormat": "Data Block Misses"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit",
     "legendFormat": "Data Block Hits"
    }
   ]
  },
  {
   "title": "Index Block Cache Hits/Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_index_miss",
     "legendFormat": "Index Block Misses"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_index_hit",
     "legendFormat": "Index Block Hits"
    }
   ]
  },
  {
   "title": "Filter Block Cache Hits/Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_filter_miss",
     "legendFormat": "Filter Block Misses"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_filter_hit",
     "legendFormat": "Filter Block Hits"
    }
   ]
  },
  {
   "title": "Overall Miss Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[1m]) / (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss[1m]) + rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit[1m]))",
     "legendFormat": "Overall Miss Rate (%)"
    }
   ]
  },
  {
   "title": "Data Miss Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_miss[1m]) / (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_miss[1m]) + rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_data_hit[1m]))",
     "legendFormat": "Data Miss Rate (%)"
    }
   ]
  },
  {
   "title": "Index Miss Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_index_miss[1m]) / (rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_index_miss[1m]) + rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_index_hit[1m]))",
     "legendFormat": "Index Miss Rate (%)"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Bytes Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_rocksdb_bytes_read[1m])",
     "legendFormat": "Bytes Read"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_rocksdb_bytes_written[1m])",
     "legendFormat": "Bytes Written"
    }
   ]
  },
  { "title": "Job Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Records In per Operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (task_name) (flink_taskmanager_job_task_numRecordsInPerSecond)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Records Out per Operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (task_name) (flink_taskmanager_job_task_numRecordsOutPerSecond)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Backpressure by Operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(flink_taskmanager_job_task_backPressuredTimeMsPerSecond / 1000) * 100",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Operator Busy %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(flink_taskmanager_job_task_busyTimeMsPerSecond / 1000) * 100",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Compactions Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_compaction_pending",
     "legendFormat": "Left compactions pending"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_compaction_pending",
     "legendFormat": "Right Compactions Pending"
    }
   ]
  },
  {
   "title": "Compactions Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_left_records_rocksdb_num_running_compactions",
     "legendFormat": "Left Compactions Running"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_right_records_rocksdb_num_running_compactions",
     "legendFormat": "Right Compactions Running"
    }
   ]
  },
  {
   "title": "RocksDB Compaction Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_compaction_key_drop_obsolete",
     "legendFormat": "key drop obsolete"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_rocksdb_compaction_key_drop_user",
     "legendFormat": "key drop user"
    },
    { "expr": "compaction", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Write Stall Micros",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_rocksdb_stall_micros[1m])",
     "legendFormat": "Write Stall Micros"
    }
   ]
  }
 ]
}