version: '3.8'
services:
  jobmanager:
    image: flink-nexmark
    ports:
      - "8081:8081"
      - "9249:9249"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9249
        # RocksDB Cache Metrics
        state.backend.rocksdb.metrics.block-cache-hit: true
        state.backend.rocksdb.metrics.block-cache-miss: true
        state.backend.rocksdb.metrics.block-cache-usage: true
        state.backend.rocksdb.metrics.block-cache-capacity: true
        # RocksDB I/O Metrics
        state.backend.rocksdb.metrics.bytes-read: true
        state.backend.rocksdb.metrics.bytes-written: true
        # RocksDB Memory & State Size Metrics
        state.backend.rocksdb.metrics.cur-size-all-mem-tables: true
        state.backend.rocksdb.metrics.size-all-mem-tables: true
        state.backend.rocksdb.metrics.estimate-table-readers-mem: true
        state.backend.rocksdb.metrics.is-write-stopped: true
        state.backend.rocksdb.metrics.num-entries-active-mem-table: true
        # RocksDB Compaction Metrics
        state.backend.rocksdb.metrics.num-running-compactions: true
        state.backend.rocksdb.metrics.num-running-flushes: true
        state.backend.rocksdb.metrics.compaction-pending: true
        state.backend.rocksdb.metrics.estimate-pending-compaction-bytes: true
        state.backend.rocksdb.metrics.compaction-write-bytes: true
        state.backend.rocksdb.metrics.compaction-read-bytes: true
        state.backend.rocksdb.metrics.estimate-num-keys: true
        state.backend.rocksdb.metrics.estimate-live-data-size: true
        state.backend.rocksdb.metrics.num-snapshots: true
        state.backend.rocksdb.metrics.stall-micros: true
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092
    networks:
      - nexmark-network
    extra_hosts:
      - "kafka1:172.18.0.3"

  taskmanager:
    image: flink-nexmark
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    ports:
      - "9249"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.cpu.cores: 8.0 
        taskmanager.numberOfTaskSlots: 2
        taskmanager.numberOfTaskManagers: 1
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9249
        # RocksDB Cache Metrics
        state.backend.rocksdb.metrics.block-cache-hit: true
        state.backend.rocksdb.metrics.block-cache-miss: true
        state.backend.rocksdb.metrics.block-cache-usage: true
        state.backend.rocksdb.metrics.block-cache-capacity: true
        # RocksDB I/O Metrics
        state.backend.rocksdb.metrics.bytes-read: true
        state.backend.rocksdb.metrics.bytes-written: true
        # RocksDB Memory & State Size Metrics
        state.backend.rocksdb.metrics.cur-size-all-mem-tables: true
        state.backend.rocksdb.metrics.size-all-mem-tables: true
        state.backend.rocksdb.metrics.estimate-table-readers-mem: true
        state.backend.rocksdb.metrics.is-write-stopped: true
        state.backend.rocksdb.metrics.num-entries-active-mem-table: true
        # RocksDB Compaction Metrics
        state.backend.rocksdb.metrics.num-running-compactions: true
        state.backend.rocksdb.metrics.num-running-flushes: true
        state.backend.rocksdb.metrics.compaction-pending: true
        state.backend.rocksdb.metrics.estimate-pending-compaction-bytes: true
        state.backend.rocksdb.metrics.compaction-write-bytes: true
        state.backend.rocksdb.metrics.compaction-read-bytes: true
        state.backend.rocksdb.metrics.estimate-num-keys: true
        state.backend.rocksdb.metrics.estimate-live-data-size: true
        state.backend.rocksdb.metrics.num-snapshots: true
        state.backend.rocksdb.metrics.stall-micros: true
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092
    networks:
      - nexmark-network
    extra_hosts:
      - "kafka1:172.18.0.3"

  prometheus:
    image: prom/prometheus:v2.44.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - nexmark-network

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    networks:
      - nexmark-network
    depends_on:
      - prometheus
  
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexmark
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - nexmark-network

  adminer:
    image: adminer
    ports:
      - "18080:8080"
    networks:
      - nexmark-network

networks:
  nexmark-network:
    external: true
    name: nexmark-bench_default

volumes:
  prometheus_data:
  grafana_data:
  postgres_data: