version: '3.8'
services:
  jobmanager:
    image: flink-nexmark
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092  # Use internal Kafka address
    networks:
      - nexmark-network
    extra_hosts:
      - "kafka1:172.18.0.3"  # Optionally map Kafka address

  taskmanager:
    image: flink-nexmark
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:19092  # Use internal Kafka address
    networks:
      - nexmark-network
    extra_hosts:
      - "kafka1:172.18.0.3"  # Optionally map Kafka address
  
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexmark
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - nexmark-network

  adminer:
    image: adminer
    ports:
      - "18080:8080"
    networks:
      - nexmark-network

networks:
  nexmark-network:
    external: true
    name: nexmark-bench_default  # Make sure this matches your Kafka network name

volumes:
  postgres_data: